CREATE TABLE VEM_SER.ESTUDANTE (
  id_estudante NUMBER NOT NULL,
  nome VARCHAR2(200) NOT NULL,
  data_nascimento DATE NOT NULL,
  nr_matricula NUMBER(10) UNIQUE NOT NULL,
  ativo CHAR(1) PRIMARY KEY(id_estudante)
);
CREATE SEQUENCE VEM_SER.SEQ_ESTUDANTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Francisca Ester Farias',
    TO_DATE('25/05/1989', 'DD/MM/YYYY'),
    23465,
    'S'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Theo Luan Matheus da Mota',
    TO_DATE('17/04/1967', 'DD/MM/YYYY'),
    897462,
    'N'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Tereza Elisa Bianca Figueiredo',
    TO_DATE('12/01/1984', 'DD/MM/YYYY'),
    7962145,
    'S'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Lucas Igor Calebe Assunção',
    TO_DATE('02/03/1993', 'DD/MM/YYYY'),
    9632157,
    'S'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Elias Caleb Vinicius Mendes',
    TO_DATE('07/02/1946', 'DD/MM/YYYY'),
    74123658,
    'N'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Heloise Lívia da Silva',
    TO_DATE('13/02/1995', 'DD/MM/YYYY'),
    3687524,
    'S'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Gael Lucca Sales',
    TO_DATE('23/01/1997', 'DD/MM/YYYY'),
    369854,
    'N'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Eduarda Maria Novaes',
    TO_DATE('02/06/1981', 'DD/MM/YYYY'),
    652398,
    'S'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Otávio Calebe Almeida',
    TO_DATE('21/01/1987', 'DD/MM/YYYY'),
    3582149,
    'N'
  );
INSERT INTO VEM_SER.ESTUDANTE
VALUES(
    VEM_SER.SEQ_ESTUDANTE.NEXTVAL,
    'Rayssa Luna Rafaela Pereira',
    TO_DATE('25/05/2001', 'DD/MM/YYYY'),
    369852,
    'S'
  );
SELECT *
FROM VEM_SER.ESTUDANTE