--Fazer um RIGHT OUTER JOIN entre tabelas:
--Pessoa e Contato
SELECT P.NOME,
  C.NUMERO
FROM PESSOA P
  RIGHT JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA);

--Pessoa, PESSOA_X_PESSOA_ENDERECO e Endereco_Pessoa
SELECT P.NOME,
  E.LOGRADOURO,
  E.NUMERO,
  E.CIDADE,
  E.ESTADO
FROM PESSOA P
  RIGHT JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  RIGHT JOIN ENDERECO_PESSOA E ON (PXPE.ID_ENDERECO = E.ID_ENDERECO);

--Todas as tabelas (começando por pessoa)
SELECT P.NOME,
  C.NUMERO,
  E.LOGRADOURO,
  E.NUMERO,
  E.CIDADE,
  E.ESTADO
FROM PESSOA P
  RIGHT JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  RIGHT JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  RIGHT JOIN ENDERECO_PESSOA E ON (PXPE.ID_ENDERECO = E.ID_ENDERECO);
--Fazer um OUTER FULL JOIN entre tabelas:
--Pessoa e Contato
SELECT P.NOME,
  C.NUMERO
FROM PESSOA P
  FULL OUTER JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA);
--Pessoa, PESSOA_X_PESSOA_ENDERECO e Endereco_Pessoa  
SELECT P.NOME,
  E.LOGRADOURO,
  E.NUMERO,
  E.CIDADE,
  E.ESTADO
FROM PESSOA P
  FULL JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN ENDERECO_PESSOA E ON (PXPE.ID_ENDERECO = E.ID_ENDERECO);
--Todas as tabelas (começando por pessoa)
SELECT P.NOME,
  C.NUMERO,
  E.LOGRADOURO,
  E.NUMERO,
  E.CIDADE,
  E.ESTADO
FROM PESSOA P
  FULL JOIN CONTATO C ON (P.ID_PESSOA = C.ID_PESSOA)
  FULL JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = PXPE.ID_PESSOA)
  FULL JOIN ENDERECO_PESSOA E ON (PXPE.ID_ENDERECO = E.ID_ENDERECO);
--Utilizando o EXISTS, selecione as pessoas que tem endereço
SELECT P.NOME
FROM PESSOA p
WHERE EXISTS (
    SELECT E.ID_ENDERECO
    FROM PESSOA_X_PESSOA_ENDERECO e
    WHERE P.ID_PESSOA = E.ID_PESSOA
  );

SELECT P.NOME,
  E.LOGRADOURO,
  E.NUMERO,
  E.CIDADE,
  E.ESTADO
FROM PESSOA P
  INNER JOIN PESSOA_X_PESSOA_ENDERECO PXPE ON (P.ID_PESSOA = pxpe.ID_PESSOA)
  INNER JOIN ENDERECO_PESSOA E ON (PXPE.ID_ENDERECO = E.ID_ENDERECO);
