--CRIANDO TABELA / SEQUENCE PAIS, PK PAIS
CREATE TABLE VEM_SER.PAIS (
  ID_PAIS NUMBER(38) NOT NULL,
  NOME VARCHAR2(50),
  PRIMARY KEY (ID_PAIS)
);
CREATE SEQUENCE VEM_SER.SEQ_PAIS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
--CRIANDO TABELA / SEQUENCE ESTADO, PK ID ESTADO, FK ID PAIS 
CREATE TABLE VEM_SER.ESTADO (
  ID_ESTADO NUMBER(38) NOT NULL,
  ID_PAIS NUMBER(38) NOT NULL,
  NOME VARCHAR2(50) UNIQUE NOT NULL,
  PRIMARY KEY(ID_ESTADO),
  CONSTRAINT FK_ID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES VEM_SER.PAIS(ID_PAIS)
);
CREATE SEQUENCE VEM_SER.SEQ_ESTADO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
--CRIANDO TABELA / SEQUENCE CIDADE, PK ID ESTADO/CIDADE, FK ID ESTADO
CREATE TABLE VEM_SER.CIDADE (
  ID_ESTADO NUMBER(38) NOT NULL,
  ID_CIDADE NUMBER(38) NOT NULL,
  NOME VARCHAR2(50) UNIQUE NOT NULL,
  PRIMARY KEY(ID_ESTADO, ID_CIDADE),
  CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES VEM_SER.ESTADO(ID_ESTADO)
);
CREATE SEQUENCE VEM_SER.SEQ_CIDADE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
--CRIANDO TABELA / SEQUENCE BAIRRO, PK ID BAIRRO/CIDADE, FK ID ESTADO
CREATE TABLE VEM_SER.BAIRRO (
  ID_BAIRRO NUMBER(38) NOT NULL,
  ID_CIDADE NUMBER(38) NOT NULL,
  ID_ESTADO NUMBER(38) NOT NULL,
  NOME VARCHAR2(50) UNIQUE NOT NULL,
  PRIMARY KEY(ID_BAIRRO, ID_CIDADE),
  CONSTRAINT FK_ID_ESTADO_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES VEM_SER.ESTADO(ID_ESTADO)
);
CREATE SEQUENCE VEM_SER.SEQ_BAIRRO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
--CRIANDO TABELA / SEQUENCE ENDERECO, PK ID ENDERECO, FK BAIRRO / CIDADE
CREATE TABLE VEM_SER.ENDERECO (
  ID_ENDERECO NUMBER(38) NOT NULL,
  ID_BAIRRO NUMBER(38) NOT NULL,
  ID_CIDADE NUMBER(38) NOT NULL,
  NOME VARCHAR2(50) UNIQUE NOT NULL,
  PRIMARY KEY(ID_ENDERECO),
  CONSTRAINT FK_ID_CIDADE_BAIRRO FOREIGN KEY (ID_CIDADE, ID_BAIRRO) REFERENCES VEM_SER.BAIRRO(ID_CIDADE, ID_BAIRRO)
);
CREATE SEQUENCE VEM_SER.SEQ_ENDERECO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
------------- EX 02 -------------
-- PAIS 1
INSERT INTO VEM_SER.PAIS
VALUES(VEM_SER.SEQ_PAIS.NEXTVAL, 'EUA');
-- PAIS 2
INSERT INTO VEM_SER.PAIS
VALUES(VEM_SER.SEQ_PAIS.NEXTVAL, 'Alemanha');
--ESTADOS PAIS 1
INSERT INTO VEM_SER.ESTADO
VALUES(
    VEM_SER.SEQ_ESTADO.NEXTVAL,
    1,
    'Colorado'
  );
INSERT INTO VEM_SER.ESTADO
VALUES(
    VEM_SER.SEQ_ESTADO.NEXTVAL,
    1,
    'Alabama'
  );
--ESTADOS PAIS 2 
INSERT INTO VEM_SER.ESTADO
VALUES(
    VEM_SER.SEQ_ESTADO.NEXTVAL,
    2,
    'Baviera'
  );
INSERT INTO VEM_SER.ESTADO
VALUES(
    VEM_SER.SEQ_ESTADO.NEXTVAL,
    2,
    "Hessen"
  );
--CIDADE ESTADO 1
INSERT INTO VEM_SER.CIDADE
VALUES(
    1,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Mobile'
  );
INSERT INTO VEM_SER.CIDADE
VALUES(
    1,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Montgomery'
  );
--CIDADE ESTADO 2   
INSERT INTO VEM_SER.CIDADE
VALUES(
    2,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Denver'
  );
INSERT INTO VEM_SER.CIDADE
VALUES(
    2,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Colorado Springs'
  );
--CIDADE ESTADO 3
INSERT INTO VEM_SER.CIDADE
VALUES(
    3,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Munique'
  );
INSERT INTO VEM_SER.CIDADE
VALUES(
    3,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Bamberg'
  );
--CIDADE ESTADO 4
INSERT INTO VEM_SER.CIDADE
VALUES(
    4,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Kassel'
  );
INSERT INTO VEM_SER.CIDADE
VALUES(
    4,
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    'Fulda'
  );

--BAIRRO CIDADE 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    18,
    1,
    'Clarkhands'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    18,
    1,
    'AppleStyle'
  );    
 
--BAIRRO CIDADE 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    19,
    1,
    'Fishburn'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    19,
    1,
    'SoulSun'
  );  

--BAIRRO CIDADE 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    20,
    2,
    'Ann Arbor'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    20,
    2,
    'Garden City'
  );
--BAIRRO CIDADE 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    21,
    2,
    'Follett'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    21,
    2,
    'Purvis'
  );
--BAIRRO CIDADE  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    22,
    3,
    'La Puente'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    22,
    3,
    'Springfield'
  ); 
--BAIRRO CIDADE 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    23,
    3,
    'Highland Park'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    23,
    3,
    'Metter'
  );
--BAIRRO CIDADE
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    24,
    4,
    'Tomball'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    24,
    4,
    'Cincinnati'
  );
--BAIRRO CIDADE
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    25,
    4,
    'Lexington'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    25,
    4,
    'Metropolis'
  );
--ENDERECO 1
INSERT INTO VEM_SER.ENDERECO
VALUES(
    VEM_SER.SEQ_ENDERECO.NEXTVAL,
    35, 
    18, 
    'Stanton Hollow Road'
  );  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    35, 
    18,
    'Davis Court'
  );
--ENDERECO 2 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    36, 
    18, 
    'Burke Street'
  );  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    36, 
    18, 
    'Broaddus Avenue'
  );
--ENDERECO 3
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    37, 
    19, 
    'Woodland Avenue'
  );  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    37, 
    19, 
    'Moore Avenue'
  );
--ENDERECO 4
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    38, 
    19, 
    'Stockbridge'
  );  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    38, 
    19, 
    'Metairie'
  );    
--ENDERECO 5 
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    39, 
    20, 
    'Jackson'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    39, 
    20, 
    'Washington'
  );
--ENDERECO 6    
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    40, 
    20, 
    'Missoula'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    40, 
    20, 
    'Cleveland'
  );
--ENDERECO 7  
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    41, 
    21, 
    'Pennsylvania'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    41, 
    21, 
    'New York'
  );
--ENDERECO 8
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    42, 
    21, 
    'San Francisco'
  );
INSERT INTO VEM_SER.BAIRRO
VALUES(
    VEM_SER.SEQ_CIDADE.NEXTVAL,
    42, 
    21, 
    'Carrollton'
  );
--CANSEI D: